sudo: false

language: java

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
 - mvn -f com.examples.MongoDBexamples/pom.xml clean verify
